/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConexaoBD;

/**
 *
 * @author esports
 */
public class TelaPrincipal extends javax.swing.JFrame {

   ConexaoBD conex = new ConexaoBD(); // faz conexao com o BD
    
    public TelaPrincipal() {
        initComponents();
        conex.conexao();// chama todas as instruções que eu fiz na Classe conexao no ConexaoBD
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalBemVindo = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        btnAgenda = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSairBemVindo = new javax.swing.JButton();
        lblFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jCadastro = new javax.swing.JMenu();
        jUsuarios = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSair = new javax.swing.JMenu();
        jItenSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalBemVindo.setTitle("Bem-vindo");
        jInternalBemVindo.setVisible(true);
        jInternalBemVindo.getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/stock-vector-people-icon-289551026.jpg"))); // NOI18N
        btnUsuario.setText("Usuario");
        btnUsuario.setToolTipText("Cadastrar Usuario");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuario);
        btnUsuario.setBounds(10, 20, 110, 90);

        btnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/stock-vector-clipboard-pencil-icon-389915557.jpg"))); // NOI18N
        btnAgenda.setText("jButton1");
        btnAgenda.setToolTipText("Usuarios Cadastrados");
        jPanel1.add(btnAgenda);
        btnAgenda.setBounds(10, 120, 110, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/pessoas-em-pe-em-forma-de-flecha_3446-294.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 10, 480, 270);

        jInternalBemVindo.getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 480, 270);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Sistema de Gerenciamento de Cadastros:");
        jInternalBemVindo.getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 290, 17);

        btnSairBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/exit.png"))); // NOI18N
        btnSairBemVindo.setToolTipText("Exit");
        btnSairBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairBemVindoActionPerformed(evt);
            }
        });
        jInternalBemVindo.getContentPane().add(btnSairBemVindo);
        btnSairBemVindo.setBounds(490, 10, 40, 30);

        getContentPane().add(jInternalBemVindo);
        jInternalBemVindo.setBounds(10, 40, 550, 350);

        lblFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/fundo_telaprincipal.jpg"))); // NOI18N
        lblFundoPrincipal.setText("jLabel1");
        getContentPane().add(lblFundoPrincipal);
        lblFundoPrincipal.setBounds(0, 0, 570, 410);

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jCadastro.setText("Cadastros");

        jUsuarios.setText("Usuarios");
        jUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsuariosActionPerformed(evt);
            }
        });
        jCadastro.add(jUsuarios);

        jMenuBar1.add(jCadastro);

        jMenu1.setText("Atalho");

        jMenuItem1.setText("Bem-vindo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jSair.setText("Sair");

        jItenSair.setText("Sair");
        jItenSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItenSairActionPerformed(evt);
            }
        });
        jSair.add(jItenSair);

        jMenuBar1.add(jSair);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 587, 467);
    }// </editor-fold>//GEN-END:initComponents

    private void jUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsuariosActionPerformed
           FormularioUsuario tela = new FormularioUsuario();// comando para quando aperta Cadastro-usuario,Abrir formulario
           tela.setVisible(true);
           dispose();
                   
    }//GEN-LAST:event_jUsuariosActionPerformed

    private void btnSairBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairBemVindoActionPerformed
        jInternalBemVindo.dispose();// Esse comando fecha a tela de cadastro:
    }//GEN-LAST:event_btnSairBemVindoActionPerformed

    private void jItenSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItenSairActionPerformed
        conex.desconecta();// Quando apertar para sair ele desconecta do BD 
        System.exit(0);// Esse comando fecha sistema por completo em Sair
    }//GEN-LAST:event_jItenSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        TelaPrincipal tela = new TelaPrincipal();//Comando para quando aperta no atalho abri tela principal
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
       FormularioUsuario tela = new FormularioUsuario();// comando para quando aperta Cadastro-usuario,Abrir formulario
           tela.setVisible(true);
           dispose();
    }//GEN-LAST:event_btnUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnSairBemVindo;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JMenu jCadastro;
    private javax.swing.JInternalFrame jInternalBemVindo;
    private javax.swing.JMenuItem jItenSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jSair;
    private javax.swing.JMenuItem jUsuarios;
    private javax.swing.JLabel lblFundoPrincipal;
    // End of variables declaration//GEN-END:variables
}
